/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogCheckAccidentsRouteImport } from './routes/blog.check-accidents'
import { Route as BlogPlateColorsRouteImport } from './routes/blog.plate-colors'
import { Route as BlogRegionCodesRouteImport } from './routes/blog.region-codes'
import { Route as NomerPlateRouteImport } from './routes/nomer.$plate'
import { Route as RegionCodeRouteImport } from './routes/region.$code'
import { Route as RuIndexRouteImport } from './routes/ru.index'
import { Route as SitemapIndexRouteImport } from './routes/sitemap.index'
import { Route as RuBlogIndexRouteImport } from './routes/ru.blog.index'
import { Route as RuBlogCheckAccidentsRouteImport } from './routes/ru.blog.check-accidents'
import { Route as RuBlogPlateColorsRouteImport } from './routes/ru.blog.plate-colors'
import { Route as RuBlogRegionCodesRouteImport } from './routes/ru.blog.region-codes'
import { Route as RuNomerPlateRouteImport } from './routes/ru.nomer.$plate'
import { Route as RuRegionCodeRouteImport } from './routes/ru.region.$code'
import { Route as RuSitemapIndexRouteImport } from './routes/ru.sitemap.index'
import { Route as SitemapCodeIndexRouteImport } from './routes/sitemap.$code.index'
import { Route as SitemapCodeSeriesRouteImport } from './routes/sitemap.$code.$series'
import { Route as ApiOgPlatePlateRouteImport } from './routes/api/og/plate.$plate'
import { Route as RuSitemapCodeIndexRouteImport } from './routes/ru.sitemap.$code.index'
import { Route as RuSitemapCodeSeriesRouteImport } from './routes/ru.sitemap.$code.$series'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCheckAccidentsRoute = BlogCheckAccidentsRouteImport.update({
  id: '/blog/check-accidents',
  path: '/blog/check-accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPlateColorsRoute = BlogPlateColorsRouteImport.update({
  id: '/blog/plate-colors',
  path: '/blog/plate-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRegionCodesRoute = BlogRegionCodesRouteImport.update({
  id: '/blog/region-codes',
  path: '/blog/region-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const NomerPlateRoute = NomerPlateRouteImport.update({
  id: '/nomer/$plate',
  path: '/nomer/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionCodeRoute = RegionCodeRouteImport.update({
  id: '/region/$code',
  path: '/region/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexRoute = SitemapIndexRouteImport.update({
  id: '/sitemap/',
  path: '/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogIndexRoute = RuBlogIndexRouteImport.update({
  id: '/ru/blog/',
  path: '/ru/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogCheckAccidentsRoute = RuBlogCheckAccidentsRouteImport.update({
  id: '/ru/blog/check-accidents',
  path: '/ru/blog/check-accidents',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogPlateColorsRoute = RuBlogPlateColorsRouteImport.update({
  id: '/ru/blog/plate-colors',
  path: '/ru/blog/plate-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const RuBlogRegionCodesRoute = RuBlogRegionCodesRouteImport.update({
  id: '/ru/blog/region-codes',
  path: '/ru/blog/region-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const RuNomerPlateRoute = RuNomerPlateRouteImport.update({
  id: '/ru/nomer/$plate',
  path: '/ru/nomer/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRegionCodeRoute = RuRegionCodeRouteImport.update({
  id: '/ru/region/$code',
  path: '/ru/region/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RuSitemapIndexRoute = RuSitemapIndexRouteImport.update({
  id: '/ru/sitemap/',
  path: '/ru/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCodeIndexRoute = SitemapCodeIndexRouteImport.update({
  id: '/sitemap/$code/',
  path: '/sitemap/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCodeSeriesRoute = SitemapCodeSeriesRouteImport.update({
  id: '/sitemap/$code/$series',
  path: '/sitemap/$code/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPlatePlateRoute = ApiOgPlatePlateRouteImport.update({
  id: '/api/og/plate/$plate',
  path: '/api/og/plate/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const RuSitemapCodeIndexRoute = RuSitemapCodeIndexRouteImport.update({
  id: '/ru/sitemap/$code/',
  path: '/ru/sitemap/$code/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuSitemapCodeSeriesRoute = RuSitemapCodeSeriesRouteImport.update({
  id: '/ru/sitemap/$code/$series',
  path: '/ru/sitemap/$code/$series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/check-accidents': typeof BlogCheckAccidentsRoute
  '/blog/plate-colors': typeof BlogPlateColorsRoute
  '/blog/region-codes': typeof BlogRegionCodesRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/ru/': typeof RuIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
  '/ru/blog/check-accidents': typeof RuBlogCheckAccidentsRoute
  '/ru/blog/plate-colors': typeof RuBlogPlateColorsRoute
  '/ru/blog/region-codes': typeof RuBlogRegionCodesRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
  '/sitemap/$code/$series': typeof SitemapCodeSeriesRoute
  '/ru/blog/': typeof RuBlogIndexRoute
  '/ru/sitemap/': typeof RuSitemapIndexRoute
  '/sitemap/$code/': typeof SitemapCodeIndexRoute
  '/api/og/plate/$plate': typeof ApiOgPlatePlateRoute
  '/ru/sitemap/$code/$series': typeof RuSitemapCodeSeriesRoute
  '/ru/sitemap/$code/': typeof RuSitemapCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/check-accidents': typeof BlogCheckAccidentsRoute
  '/blog/plate-colors': typeof BlogPlateColorsRoute
  '/blog/region-codes': typeof BlogRegionCodesRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/blog': typeof BlogIndexRoute
  '/ru': typeof RuIndexRoute
  '/sitemap': typeof SitemapIndexRoute
  '/ru/blog/check-accidents': typeof RuBlogCheckAccidentsRoute
  '/ru/blog/plate-colors': typeof RuBlogPlateColorsRoute
  '/ru/blog/region-codes': typeof RuBlogRegionCodesRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
  '/sitemap/$code/$series': typeof SitemapCodeSeriesRoute
  '/ru/blog': typeof RuBlogIndexRoute
  '/ru/sitemap': typeof RuSitemapIndexRoute
  '/sitemap/$code': typeof SitemapCodeIndexRoute
  '/api/og/plate/$plate': typeof ApiOgPlatePlateRoute
  '/ru/sitemap/$code/$series': typeof RuSitemapCodeSeriesRoute
  '/ru/sitemap/$code': typeof RuSitemapCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/check-accidents': typeof BlogCheckAccidentsRoute
  '/blog/plate-colors': typeof BlogPlateColorsRoute
  '/blog/region-codes': typeof BlogRegionCodesRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/ru/': typeof RuIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
  '/ru/blog/check-accidents': typeof RuBlogCheckAccidentsRoute
  '/ru/blog/plate-colors': typeof RuBlogPlateColorsRoute
  '/ru/blog/region-codes': typeof RuBlogRegionCodesRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
  '/sitemap/$code/$series': typeof SitemapCodeSeriesRoute
  '/ru/blog/': typeof RuBlogIndexRoute
  '/ru/sitemap/': typeof RuSitemapIndexRoute
  '/sitemap/$code/': typeof SitemapCodeIndexRoute
  '/api/og/plate/$plate': typeof ApiOgPlatePlateRoute
  '/ru/sitemap/$code/$series': typeof RuSitemapCodeSeriesRoute
  '/ru/sitemap/$code/': typeof RuSitemapCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/check-accidents'
    | '/blog/plate-colors'
    | '/blog/region-codes'
    | '/nomer/$plate'
    | '/region/$code'
    | '/blog/'
    | '/ru/'
    | '/sitemap/'
    | '/ru/blog/check-accidents'
    | '/ru/blog/plate-colors'
    | '/ru/blog/region-codes'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
    | '/sitemap/$code/$series'
    | '/ru/blog/'
    | '/ru/sitemap/'
    | '/sitemap/$code/'
    | '/api/og/plate/$plate'
    | '/ru/sitemap/$code/$series'
    | '/ru/sitemap/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/check-accidents'
    | '/blog/plate-colors'
    | '/blog/region-codes'
    | '/nomer/$plate'
    | '/region/$code'
    | '/blog'
    | '/ru'
    | '/sitemap'
    | '/ru/blog/check-accidents'
    | '/ru/blog/plate-colors'
    | '/ru/blog/region-codes'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
    | '/sitemap/$code/$series'
    | '/ru/blog'
    | '/ru/sitemap'
    | '/sitemap/$code'
    | '/api/og/plate/$plate'
    | '/ru/sitemap/$code/$series'
    | '/ru/sitemap/$code'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/check-accidents'
    | '/blog/plate-colors'
    | '/blog/region-codes'
    | '/nomer/$plate'
    | '/region/$code'
    | '/blog/'
    | '/ru/'
    | '/sitemap/'
    | '/ru/blog/check-accidents'
    | '/ru/blog/plate-colors'
    | '/ru/blog/region-codes'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
    | '/sitemap/$code/$series'
    | '/ru/blog/'
    | '/ru/sitemap/'
    | '/sitemap/$code/'
    | '/api/og/plate/$plate'
    | '/ru/sitemap/$code/$series'
    | '/ru/sitemap/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogCheckAccidentsRoute: typeof BlogCheckAccidentsRoute
  BlogPlateColorsRoute: typeof BlogPlateColorsRoute
  BlogRegionCodesRoute: typeof BlogRegionCodesRoute
  NomerPlateRoute: typeof NomerPlateRoute
  RegionCodeRoute: typeof RegionCodeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RuIndexRoute: typeof RuIndexRoute
  SitemapIndexRoute: typeof SitemapIndexRoute
  RuBlogCheckAccidentsRoute: typeof RuBlogCheckAccidentsRoute
  RuBlogPlateColorsRoute: typeof RuBlogPlateColorsRoute
  RuBlogRegionCodesRoute: typeof RuBlogRegionCodesRoute
  RuNomerPlateRoute: typeof RuNomerPlateRoute
  RuRegionCodeRoute: typeof RuRegionCodeRoute
  SitemapCodeSeriesRoute: typeof SitemapCodeSeriesRoute
  RuBlogIndexRoute: typeof RuBlogIndexRoute
  RuSitemapIndexRoute: typeof RuSitemapIndexRoute
  SitemapCodeIndexRoute: typeof SitemapCodeIndexRoute
  ApiOgPlatePlateRoute: typeof ApiOgPlatePlateRoute
  RuSitemapCodeSeriesRoute: typeof RuSitemapCodeSeriesRoute
  RuSitemapCodeIndexRoute: typeof RuSitemapCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/check-accidents': {
      id: '/blog/check-accidents'
      path: '/blog/check-accidents'
      fullPath: '/blog/check-accidents'
      preLoaderRoute: typeof BlogCheckAccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/plate-colors': {
      id: '/blog/plate-colors'
      path: '/blog/plate-colors'
      fullPath: '/blog/plate-colors'
      preLoaderRoute: typeof BlogPlateColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/region-codes': {
      id: '/blog/region-codes'
      path: '/blog/region-codes'
      fullPath: '/blog/region-codes'
      preLoaderRoute: typeof BlogRegionCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomer/$plate': {
      id: '/nomer/$plate'
      path: '/nomer/$plate'
      fullPath: '/nomer/$plate'
      preLoaderRoute: typeof NomerPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$code': {
      id: '/region/$code'
      path: '/region/$code'
      fullPath: '/region/$code'
      preLoaderRoute: typeof RegionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/': {
      id: '/sitemap/'
      path: '/sitemap'
      fullPath: '/sitemap/'
      preLoaderRoute: typeof SitemapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog/': {
      id: '/ru/blog/'
      path: '/ru/blog'
      fullPath: '/ru/blog/'
      preLoaderRoute: typeof RuBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog/check-accidents': {
      id: '/ru/blog/check-accidents'
      path: '/ru/blog/check-accidents'
      fullPath: '/ru/blog/check-accidents'
      preLoaderRoute: typeof RuBlogCheckAccidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog/plate-colors': {
      id: '/ru/blog/plate-colors'
      path: '/ru/blog/plate-colors'
      fullPath: '/ru/blog/plate-colors'
      preLoaderRoute: typeof RuBlogPlateColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/blog/region-codes': {
      id: '/ru/blog/region-codes'
      path: '/ru/blog/region-codes'
      fullPath: '/ru/blog/region-codes'
      preLoaderRoute: typeof RuBlogRegionCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/nomer/$plate': {
      id: '/ru/nomer/$plate'
      path: '/ru/nomer/$plate'
      fullPath: '/ru/nomer/$plate'
      preLoaderRoute: typeof RuNomerPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/region/$code': {
      id: '/ru/region/$code'
      path: '/ru/region/$code'
      fullPath: '/ru/region/$code'
      preLoaderRoute: typeof RuRegionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/sitemap/': {
      id: '/ru/sitemap/'
      path: '/ru/sitemap'
      fullPath: '/ru/sitemap/'
      preLoaderRoute: typeof RuSitemapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$code/': {
      id: '/sitemap/$code/'
      path: '/sitemap/$code'
      fullPath: '/sitemap/$code/'
      preLoaderRoute: typeof SitemapCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$code/$series': {
      id: '/sitemap/$code/$series'
      path: '/sitemap/$code/$series'
      fullPath: '/sitemap/$code/$series'
      preLoaderRoute: typeof SitemapCodeSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/plate/$plate': {
      id: '/api/og/plate/$plate'
      path: '/api/og/plate/$plate'
      fullPath: '/api/og/plate/$plate'
      preLoaderRoute: typeof ApiOgPlatePlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/sitemap/$code/': {
      id: '/ru/sitemap/$code/'
      path: '/ru/sitemap/$code'
      fullPath: '/ru/sitemap/$code/'
      preLoaderRoute: typeof RuSitemapCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/sitemap/$code/$series': {
      id: '/ru/sitemap/$code/$series'
      path: '/ru/sitemap/$code/$series'
      fullPath: '/ru/sitemap/$code/$series'
      preLoaderRoute: typeof RuSitemapCodeSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogCheckAccidentsRoute: BlogCheckAccidentsRoute,
  BlogPlateColorsRoute: BlogPlateColorsRoute,
  BlogRegionCodesRoute: BlogRegionCodesRoute,
  NomerPlateRoute: NomerPlateRoute,
  RegionCodeRoute: RegionCodeRoute,
  BlogIndexRoute: BlogIndexRoute,
  RuIndexRoute: RuIndexRoute,
  SitemapIndexRoute: SitemapIndexRoute,
  RuBlogCheckAccidentsRoute: RuBlogCheckAccidentsRoute,
  RuBlogPlateColorsRoute: RuBlogPlateColorsRoute,
  RuBlogRegionCodesRoute: RuBlogRegionCodesRoute,
  RuNomerPlateRoute: RuNomerPlateRoute,
  RuRegionCodeRoute: RuRegionCodeRoute,
  SitemapCodeSeriesRoute: SitemapCodeSeriesRoute,
  RuBlogIndexRoute: RuBlogIndexRoute,
  RuSitemapIndexRoute: RuSitemapIndexRoute,
  SitemapCodeIndexRoute: SitemapCodeIndexRoute,
  ApiOgPlatePlateRoute: ApiOgPlatePlateRoute,
  RuSitemapCodeSeriesRoute: RuSitemapCodeSeriesRoute,
  RuSitemapCodeIndexRoute: RuSitemapCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
