/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NomerPlateRouteImport } from './routes/nomer.$plate'
import { Route as RegionCodeRouteImport } from './routes/region.$code'
import { Route as RuIndexRouteImport } from './routes/ru.index'
import { Route as RuNomerPlateRouteImport } from './routes/ru.nomer.$plate'
import { Route as RuRegionCodeRouteImport } from './routes/ru.region.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NomerPlateRoute = NomerPlateRouteImport.update({
  id: '/nomer/$plate',
  path: '/nomer/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionCodeRoute = RegionCodeRouteImport.update({
  id: '/region/$code',
  path: '/region/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RuIndexRoute = RuIndexRouteImport.update({
  id: '/ru/',
  path: '/ru/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuNomerPlateRoute = RuNomerPlateRouteImport.update({
  id: '/ru/nomer/$plate',
  path: '/ru/nomer/$plate',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRegionCodeRoute = RuRegionCodeRouteImport.update({
  id: '/ru/region/$code',
  path: '/ru/region/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/ru/': typeof RuIndexRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/ru': typeof RuIndexRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/nomer/$plate': typeof NomerPlateRoute
  '/region/$code': typeof RegionCodeRoute
  '/ru/': typeof RuIndexRoute
  '/ru/nomer/$plate': typeof RuNomerPlateRoute
  '/ru/region/$code': typeof RuRegionCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/nomer/$plate'
    | '/region/$code'
    | '/ru/'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/nomer/$plate'
    | '/region/$code'
    | '/ru'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/nomer/$plate'
    | '/region/$code'
    | '/ru/'
    | '/ru/nomer/$plate'
    | '/ru/region/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NomerPlateRoute: typeof NomerPlateRoute
  RegionCodeRoute: typeof RegionCodeRoute
  RuIndexRoute: typeof RuIndexRoute
  RuNomerPlateRoute: typeof RuNomerPlateRoute
  RuRegionCodeRoute: typeof RuRegionCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomer/$plate': {
      id: '/nomer/$plate'
      path: '/nomer/$plate'
      fullPath: '/nomer/$plate'
      preLoaderRoute: typeof NomerPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$code': {
      id: '/region/$code'
      path: '/region/$code'
      fullPath: '/region/$code'
      preLoaderRoute: typeof RegionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/': {
      id: '/ru/'
      path: '/ru'
      fullPath: '/ru/'
      preLoaderRoute: typeof RuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/nomer/$plate': {
      id: '/ru/nomer/$plate'
      path: '/ru/nomer/$plate'
      fullPath: '/ru/nomer/$plate'
      preLoaderRoute: typeof RuNomerPlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru/region/$code': {
      id: '/ru/region/$code'
      path: '/ru/region/$code'
      fullPath: '/ru/region/$code'
      preLoaderRoute: typeof RuRegionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NomerPlateRoute: NomerPlateRoute,
  RegionCodeRoute: RegionCodeRoute,
  RuIndexRoute: RuIndexRoute,
  RuNomerPlateRoute: RuNomerPlateRoute,
  RuRegionCodeRoute: RuRegionCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
